name: wedding
favicon: null
layout_spectrum: 0.3668212085030973
typography_spectrum: 0.5655752134043723
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6507305621635169
  lightness: 0.8917625779286027
  saturation: 0.3853193689137697
  rhythmicContrast: 0.6494962684810162
purpose: []
